{{- /* Optional secret injection */ -}}
{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "toron.fullname" . }}
  labels:
    app: {{ include "toron.name" . }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
