metrics_namespace: Toron/Service
allowed_error_rate: 0.02
allowed_latency_ms: 350
latency_budget_ms: 280
steps: [1, 5, 10, 25, 50, 100]
step_durations: [300, 300, 600, 900, 900, 1200]
watchdog_interval_seconds: 180
sns_topic: arn:aws:sns:us-east-1:123456789012:toron-canary-events
route53_zone_id: ZONE1234
route53_record: api.toron.ai
stable_environment: blue
canary_environment: green
stable_alias_target:
  HostedZoneId: Z35SXDOTRQ7X7K
  DNSName: dualstack/toron-blue-alb.amazonaws.com
  EvaluateTargetHealth: true
canary_alias_target:
  HostedZoneId: Z35SXDOTRQ7X7K
  DNSName: dualstack/toron-green-alb.amazonaws.com
  EvaluateTargetHealth: true
