apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ryuzen-engine.fullname" . }}
  labels:
    {{- include "ryuzen-engine.labels" . | nindent 4 }}
type: Opaque
data:
  secret_key: {{ .Values.env.secretKey | b64enc | quote }}
