apiVersion: v1
kind: Secret
metadata:
  name: toron-secrets
  namespace: toron-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/toron-engine-irsa
stringData:
  secrets_manager_arn: arn:aws:secretsmanager:us-east-1:123456789012:secret:toron/engine
