apiVersion: v1
kind: Service
metadata:
  name: toron-engine
  namespace: toron-prod
  labels:
    app: toron-engine
spec:
  selector:
    app: toron-engine
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
