apiVersion: v1
kind: Service
metadata:
  name: toron-engine
  labels:
    app: toron-engine
spec:
  type: ClusterIP
  selector:
    app: toron-engine
  ports:
    - name: http
      port: 80
      targetPort: 8080
