version: "3.9"
services:
  toron:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: toron-engine:latest
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    restart: always
    command: python src/backend/server.py
