apiVersion: v1
kind: Service
metadata:
  name: ryuzen-engine
  labels:
    app: ryuzen-engine
spec:
  selector:
    app: ryuzen-engine
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
